name: CI
on: [push, pull_request]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack start notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/pycyapi/main/de.png
          SLACK_MESSAGE: 'Build started'
          SLACK_TITLE: PyCyAPI
          SLACK_USERNAME: pycyapi
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # install python deps
          python -m pip install --upgrade pip
          pip install flake8 pytest coveralls setuptools wheel twine
          pip install -e .
      - name: Lint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          coverage run --source=pycyapi -m pytest /home/runner/work/pycyapi/pycyapi/pycyapi/tests/unit -s
          coveralls
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        env:
          SINGULARITY_VERSION: ${{ secrets.SINGULARITY_VERSION }}
        run: |
          # python
          python -m pip install --upgrade pip
          pip install flake8 pytest coveralls setuptools wheel twine
          pip install -e .
      - name: Lint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test
        env:
          CYVERSE_USERNAME: ${{ secrets.CYVERSE_USERNAME }}
          CYVERSE_PASSWORD: ${{ secrets.CYVERSE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          coverage run --source=pycyapi -m pytest /home/runner/work/pycyapi/pycyapi/pycyapi/tests/integration -s
          coveralls
      - name: Update Coveralls
        run: |
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # python
          python -m pip install --upgrade pip
          pip install flake8 pytest coveralls setuptools wheel twine
          pip install -e .
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          skip_existing: true
      - name: Slack success notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: plantit-dev
          SLACK_ICON: https://raw.githubusercontent.com/Computational-Plant-Science/pycyapi/main/de.png
          SLACK_MESSAGE: 'Build succeeded'
          SLACK_TITLE: PyCyAPI
          SLACK_USERNAME: pycyapi